USE [master]
GO

/****** Object:  Database [Wevo]    Script Date: 29/05/2019 22:44:39 ******/
CREATE DATABASE [Wevo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Wevo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Wevo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Wevo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Wevo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Wevo] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Wevo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Wevo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Wevo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Wevo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Wevo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Wevo] SET ARITHABORT OFF 
GO

ALTER DATABASE [Wevo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Wevo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Wevo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Wevo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Wevo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Wevo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Wevo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Wevo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Wevo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Wevo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Wevo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Wevo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Wevo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Wevo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Wevo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Wevo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Wevo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Wevo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Wevo] SET  MULTI_USER 
GO

ALTER DATABASE [Wevo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Wevo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Wevo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Wevo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Wevo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Wevo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Wevo] SET  READ_WRITE 
GO

USE [Wevo]
GO

/****** Object:  Table [dbo].[Usuarios]    Script Date: 29/05/2019 22:44:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](400) NULL,
	[CPF] [varchar](16) NULL,
	[Email] [varchar](150) NULL,
	[Telefone] [varchar](30) NULL,
	[Sexo] [char](2) NULL,
	[DataNascimento] [datetime] NULL,
 CONSTRAINT [PK_Usuarios] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

